import { Metadata } from "next";

export const metadata: Metadata = {
  title: "About | Next App",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <div className="bg-white">
      <h3 className="my-4 text-xl">Select subitem</h3>
    </div>
  );
}
